apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toymodel-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nike541/AI-Model-CI-CD.git
    targetRevision: HEAD
    path: k8s/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true