apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: toymodel-staging
    namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nike541/AI-Model-CI-CD.git
    targetRevision: HEAD
    path: k8s/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true