apiVersion: v1
kind: Service
metadata:
  name: toymodel-stable
spec:
  selector:
    app: toymodel
  ports:
  - name: http
    port: 8000
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: toymodel-canary
spec:
  selector:
    app: toymodel
  ports:
  - name: http
    port: 8000
    targetPort: http