apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: toymodel
spec:
  selector:
    matchLabels:
      app: toymodel
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 14s