apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: litmodel
spec:
  selector:
    matchLabels:
      app: litmodel
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 14s